sudo: required
language: node_js
node_js:
  - 14 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - main # build master branch only
script:
  - hexo g # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public
  matrix:
  include:
    - dist: bionic
    - dist: focal
